import type { CompareData } from './types';

export const MOCK_COMPARE_DATA: CompareData = {
  apps: [
    { key: 'shinhan', name: '신한 SOL뱅크', isSelf: true,  color: '#0046ff' },
    { key: 'toss',    name: '토스',         isSelf: false, color: '#3182f6' },
    { key: 'kakao',   name: '카카오뱅크',   isSelf: false, color: '#f9e000' },
    { key: 'kb',      name: 'KB스타뱅킹',   isSelf: false, color: '#bc1c3d' },
    { key: 'hana',    name: '하나원큐',      isSelf: false, color: '#008855' },
    { key: 'woori',   name: '우리WON뱅킹',  isSelf: false, color: '#004b9d' },
  ],

  stats: [
    { appKey: 'shinhan', avgRating: 3.8, reviewCount: 42000,  positiveRate: 52, negativeRate: 31, neutralRate: 17 },
    { appKey: 'toss',    avgRating: 4.5, reviewCount: 180000, positiveRate: 73, negativeRate: 14, neutralRate: 13 },
    { appKey: 'kakao',   avgRating: 4.3, reviewCount: 95000,  positiveRate: 68, negativeRate: 18, neutralRate: 14 },
    { appKey: 'kb',      avgRating: 3.5, reviewCount: 38000,  positiveRate: 44, negativeRate: 38, neutralRate: 18 },
    { appKey: 'hana',    avgRating: 3.6, reviewCount: 29000,  positiveRate: 47, negativeRate: 35, neutralRate: 18 },
    { appKey: 'woori',   avgRating: 3.7, reviewCount: 25000,  positiveRate: 50, negativeRate: 32, neutralRate: 18 },
  ],

  painPoints: [
    // 신한
    { appKey: 'shinhan', category: '로그인 문제',      score: 55, count: 1230 },
    { appKey: 'shinhan', category: '인증/보안',         score: 68, count: 1890 },
    { appKey: 'shinhan', category: '이체/송금 오류',   score: 42, count: 870  },
    { appKey: 'shinhan', category: '앱 속도/성능',     score: 61, count: 1540 },
    { appKey: 'shinhan', category: 'UI/UX 불편',       score: 58, count: 1320 },
    { appKey: 'shinhan', category: '업데이트 오류',    score: 72, count: 2100 },
    { appKey: 'shinhan', category: '알림 문제',         score: 38, count: 710  },
    { appKey: 'shinhan', category: '고객센터',          score: 44, count: 920  },
    { appKey: 'shinhan', category: '계좌/카드 연동',   score: 47, count: 1010 },
    { appKey: 'shinhan', category: '해외 이용',         score: 33, count: 540  },
    // 토스
    { appKey: 'toss',    category: '로그인 문제',      score: 18, count: 680  },
    { appKey: 'toss',    category: '인증/보안',         score: 22, count: 890  },
    { appKey: 'toss',    category: '이체/송금 오류',   score: 15, count: 520  },
    { appKey: 'toss',    category: '앱 속도/성능',     score: 20, count: 760  },
    { appKey: 'toss',    category: 'UI/UX 불편',       score: 12, count: 430  },
    { appKey: 'toss',    category: '업데이트 오류',    score: 16, count: 610  },
    { appKey: 'toss',    category: '알림 문제',         score: 11, count: 390  },
    { appKey: 'toss',    category: '고객센터',          score: 24, count: 920  },
    { appKey: 'toss',    category: '계좌/카드 연동',   score: 19, count: 710  },
    { appKey: 'toss',    category: '해외 이용',         score: 14, count: 510  },
    // 카카오
    { appKey: 'kakao',   category: '로그인 문제',      score: 22, count: 780  },
    { appKey: 'kakao',   category: '인증/보안',         score: 28, count: 1010 },
    { appKey: 'kakao',   category: '이체/송금 오류',   score: 20, count: 680  },
    { appKey: 'kakao',   category: '앱 속도/성능',     score: 25, count: 870  },
    { appKey: 'kakao',   category: 'UI/UX 불편',       score: 18, count: 590  },
    { appKey: 'kakao',   category: '업데이트 오류',    score: 21, count: 730  },
    { appKey: 'kakao',   category: '알림 문제',         score: 15, count: 480  },
    { appKey: 'kakao',   category: '고객센터',          score: 30, count: 1050 },
    { appKey: 'kakao',   category: '계좌/카드 연동',   score: 23, count: 790  },
    { appKey: 'kakao',   category: '해외 이용',         score: 17, count: 570  },
    // KB
    { appKey: 'kb',      category: '로그인 문제',      score: 62, count: 1110 },
    { appKey: 'kb',      category: '인증/보안',         score: 58, count: 980  },
    { appKey: 'kb',      category: '이체/송금 오류',   score: 50, count: 820  },
    { appKey: 'kb',      category: '앱 속도/성능',     score: 70, count: 1350 },
    { appKey: 'kb',      category: 'UI/UX 불편',       score: 75, count: 1480 },
    { appKey: 'kb',      category: '업데이트 오류',    score: 65, count: 1220 },
    { appKey: 'kb',      category: '알림 문제',         score: 42, count: 720  },
    { appKey: 'kb',      category: '고객센터',          score: 55, count: 960  },
    { appKey: 'kb',      category: '계좌/카드 연동',   score: 48, count: 810  },
    { appKey: 'kb',      category: '해외 이용',         score: 38, count: 590  },
    // 하나
    { appKey: 'hana',    category: '로그인 문제',      score: 57, count: 890  },
    { appKey: 'hana',    category: '인증/보안',         score: 52, count: 810  },
    { appKey: 'hana',    category: '이체/송금 오류',   score: 45, count: 680  },
    { appKey: 'hana',    category: '앱 속도/성능',     score: 63, count: 1020 },
    { appKey: 'hana',    category: 'UI/UX 불편',       score: 68, count: 1120 },
    { appKey: 'hana',    category: '업데이트 오류',    score: 60, count: 970  },
    { appKey: 'hana',    category: '알림 문제',         score: 39, count: 600  },
    { appKey: 'hana',    category: '고객센터',          score: 50, count: 790  },
    { appKey: 'hana',    category: '계좌/카드 연동',   score: 44, count: 680  },
    { appKey: 'hana',    category: '해외 이용',         score: 35, count: 520  },
    // 우리
    { appKey: 'woori',   category: '로그인 문제',      score: 50, count: 750  },
    { appKey: 'woori',   category: '인증/보안',         score: 46, count: 690  },
    { appKey: 'woori',   category: '이체/송금 오류',   score: 40, count: 580  },
    { appKey: 'woori',   category: '앱 속도/성능',     score: 55, count: 840  },
    { appKey: 'woori',   category: 'UI/UX 불편',       score: 60, count: 920  },
    { appKey: 'woori',   category: '업데이트 오류',    score: 52, count: 790  },
    { appKey: 'woori',   category: '알림 문제',         score: 35, count: 520  },
    { appKey: 'woori',   category: '고객센터',          score: 45, count: 670  },
    { appKey: 'woori',   category: '계좌/카드 연동',   score: 42, count: 630  },
    { appKey: 'woori',   category: '해외 이용',         score: 30, count: 440  },
  ],

  trend: [
    { month: '2024-10', appKey: 'shinhan', avgRating: 3.7 },
    { month: '2024-11', appKey: 'shinhan', avgRating: 3.6 },
    { month: '2024-12', appKey: 'shinhan', avgRating: 3.8 },
    { month: '2024-10', appKey: 'toss',    avgRating: 4.4 },
    { month: '2024-11', appKey: 'toss',    avgRating: 4.5 },
    { month: '2024-12', appKey: 'toss',    avgRating: 4.5 },
    { month: '2024-10', appKey: 'kakao',   avgRating: 4.2 },
    { month: '2024-11', appKey: 'kakao',   avgRating: 4.3 },
    { month: '2024-12', appKey: 'kakao',   avgRating: 4.3 },
    { month: '2024-10', appKey: 'kb',      avgRating: 3.6 },
    { month: '2024-11', appKey: 'kb',      avgRating: 3.4 },
    { month: '2024-12', appKey: 'kb',      avgRating: 3.5 },
    { month: '2024-10', appKey: 'hana',    avgRating: 3.7 },
    { month: '2024-11', appKey: 'hana',    avgRating: 3.5 },
    { month: '2024-12', appKey: 'hana',    avgRating: 3.6 },
    { month: '2024-10', appKey: 'woori',   avgRating: 3.6 },
    { month: '2024-11', appKey: 'woori',   avgRating: 3.7 },
    { month: '2024-12', appKey: 'woori',   avgRating: 3.7 },
  ],

  reviews: [
    // 신한
    { id: 'r01', appKey: 'shinhan', platform: 'google_play', rating: 1, date: '2024-12-10', sentiment: 'negative', painCategories: ['업데이트 오류'], content: '업데이트하고 나서 앱이 계속 튕겨요. 로그인이 아예 안 됩니다. 빠른 조치 부탁드립니다.' },
    { id: 'r02', appKey: 'shinhan', platform: 'app_store',   rating: 2, date: '2024-12-05', sentiment: 'negative', painCategories: ['인증/보안'], content: '공인인증서 갱신할 때마다 오류가 납니다. 다른 앱들은 이런 문제가 없는데 신한만 유독 불편하네요.' },
    { id: 'r03', appKey: 'shinhan', platform: 'google_play', rating: 4, date: '2024-11-20', sentiment: 'positive', painCategories: [], content: '전반적으로 사용하기 편리하고, 이체 기능은 빠르게 잘 됩니다. 다만 UI가 조금 복잡한 느낌이에요.' },
    { id: 'r04', appKey: 'shinhan', platform: 'app_store',   rating: 5, date: '2024-11-15', sentiment: 'positive', painCategories: [], content: '모임통장 기능이 정말 편리합니다. 자주 쓰는 기능이라 만족도가 높아요.' },
    { id: 'r05', appKey: 'shinhan', platform: 'google_play', rating: 3, date: '2024-10-30', sentiment: 'neutral',  painCategories: ['앱 속도/성능'], content: '평소엔 괜찮은데 가끔 느릴 때가 있어요. 전체적으로 평범한 수준입니다.' },
    { id: 'r06', appKey: 'shinhan', platform: 'app_store',   rating: 1, date: '2024-12-18', sentiment: 'negative', painCategories: ['인증/보안', '업데이트 오류'], content: '업데이트 후 생체인증이 초기화되고 재등록도 안 됩니다. 업무에 지장이 크네요.' },
    // 토스
    { id: 'r07', appKey: 'toss', platform: 'google_play', rating: 5, date: '2024-12-12', sentiment: 'positive', painCategories: [], content: '디자인이 정말 깔끔하고 직관적이에요. 처음 쓰는 사람도 바로 이해할 수 있을 것 같아요.' },
    { id: 'r08', appKey: 'toss', platform: 'app_store',   rating: 5, date: '2024-12-08', sentiment: 'positive', painCategories: [], content: '송금이 이렇게 쉬울 수가 없어요. 전화번호 하나로 바로 되니까 너무 편합니다.' },
    { id: 'r09', appKey: 'toss', platform: 'google_play', rating: 2, date: '2024-11-22', sentiment: 'negative', painCategories: ['고객센터'], content: '문제가 생겼는데 고객센터 연결이 너무 어렵습니다. 챗봇만 있고 사람이랑 연결이 안 돼요.' },
    { id: 'r10', appKey: 'toss', platform: 'app_store',   rating: 4, date: '2024-11-10', sentiment: 'positive', painCategories: [], content: '자산 관리 기능이 유용해요. 어디서 얼마나 썼는지 한눈에 보여서 지출 파악이 쉽습니다.' },
    { id: 'r11', appKey: 'toss', platform: 'google_play', rating: 3, date: '2024-10-25', sentiment: 'neutral',  painCategories: ['알림 문제'], content: '알림이 가끔 늦게 오는 경우가 있어요. 송금 완료 알림이 10분 뒤에 오기도 했습니다.' },
    // 카카오
    { id: 'r12', appKey: 'kakao', platform: 'google_play', rating: 5, date: '2024-12-14', sentiment: 'positive', painCategories: [], content: '카카오뱅크는 정말 편해요. 통장 개설도 5분 만에 끝났고 이체도 간편합니다.' },
    { id: 'r13', appKey: 'kakao', platform: 'app_store',   rating: 4, date: '2024-12-01', sentiment: 'positive', painCategories: [], content: '26주 적금 기능이 재미있고 도움이 됩니다. 저축 동기 부여가 확실하게 됩니다.' },
    { id: 'r14', appKey: 'kakao', platform: 'google_play', rating: 2, date: '2024-11-18', sentiment: 'negative', painCategories: ['고객센터'], content: '오류가 생겼을 때 고객센터 응답이 너무 느립니다. 이틀 뒤에 답변 와서 황당했어요.' },
    { id: 'r15', appKey: 'kakao', platform: 'app_store',   rating: 3, date: '2024-10-28', sentiment: 'neutral',  painCategories: ['계좌/카드 연동'], content: '타행 계좌 연동이 가끔 실패해요. 재시도하면 되긴 하는데 번거롭습니다.' },
    // KB
    { id: 'r16', appKey: 'kb', platform: 'google_play', rating: 1, date: '2024-12-16', sentiment: 'negative', painCategories: ['UI/UX 불편', '앱 속도/성능'], content: 'UI가 너무 복잡해요. 원하는 메뉴 찾기가 너무 어렵고 앱도 자꾸 느려집니다.' },
    { id: 'r17', appKey: 'kb', platform: 'app_store',   rating: 2, date: '2024-12-03', sentiment: 'negative', painCategories: ['로그인 문제'], content: '지문 인식이 작동을 안 해서 매번 비밀번호 치고 있어요. 개선이 필요합니다.' },
    { id: 'r18', appKey: 'kb', platform: 'google_play', rating: 4, date: '2024-11-25', sentiment: 'positive', painCategories: [], content: '주식 연계 기능은 편리합니다. KB증권이랑 연동해서 보기 좋아요.' },
    { id: 'r19', appKey: 'kb', platform: 'app_store',   rating: 3, date: '2024-10-20', sentiment: 'neutral',  painCategories: ['업데이트 오류'], content: '업데이트 후 일부 기능이 안 되는 경우가 있었어요. 곧 수정되긴 했습니다.' },
    // 하나
    { id: 'r20', appKey: 'hana', platform: 'google_play', rating: 1, date: '2024-12-09', sentiment: 'negative', painCategories: ['UI/UX 불편'], content: '메뉴 구조가 너무 복잡합니다. 이체 한 번 하려면 몇 단계를 거쳐야 하는지 모르겠어요.' },
    { id: 'r21', appKey: 'hana', platform: 'app_store',   rating: 4, date: '2024-11-30', sentiment: 'positive', painCategories: [], content: '환전 서비스가 편리합니다. 공항 픽업까지 되어서 해외여행 전에 유용하게 썼어요.' },
    { id: 'r22', appKey: 'hana', platform: 'google_play', rating: 3, date: '2024-10-15', sentiment: 'neutral',  painCategories: ['앱 속도/성능'], content: '앱 자체는 나쁘지 않은데 아침 출근 시간대에 느려지는 경우가 가끔 있습니다.' },
    // 우리
    { id: 'r23', appKey: 'woori', platform: 'google_play', rating: 2, date: '2024-12-11', sentiment: 'negative', painCategories: ['UI/UX 불편', '앱 속도/성능'], content: '앱이 구식 느낌이에요. 다른 은행 앱들에 비해 UI가 많이 뒤처지는 것 같습니다.' },
    { id: 'r24', appKey: 'woori', platform: 'app_store',   rating: 4, date: '2024-11-28', sentiment: 'positive', painCategories: [], content: '위비 포인트 적립이 쏠쏠해요. 이벤트도 자주 해서 혜택이 제법 됩니다.' },
    { id: 'r25', appKey: 'woori', platform: 'google_play', rating: 3, date: '2024-10-22', sentiment: 'neutral',  painCategories: ['알림 문제'], content: '기능은 충분한데 알림 설정이 직관적이지 않아서 조금 헷갈렸습니다.' },
  ],

  keywords: [
    // 신한
    { appKey: 'shinhan', word: '업데이트',   count: 2100 },
    { appKey: 'shinhan', word: '오류',       count: 1980 },
    { appKey: 'shinhan', word: '인증서',     count: 1540 },
    { appKey: 'shinhan', word: '느림',       count: 1320 },
    { appKey: 'shinhan', word: '튕김',       count: 1200 },
    { appKey: 'shinhan', word: '이체',       count: 980  },
    { appKey: 'shinhan', word: '모임통장',   count: 870  },
    { appKey: 'shinhan', word: '편리',       count: 760  },
    { appKey: 'shinhan', word: '생체인증',   count: 710  },
    { appKey: 'shinhan', word: '개선',       count: 650  },
    // 토스
    { appKey: 'toss', word: '간편',     count: 4200 },
    { appKey: 'toss', word: '송금',     count: 3900 },
    { appKey: 'toss', word: '직관적',   count: 3400 },
    { appKey: 'toss', word: '빠름',     count: 3100 },
    { appKey: 'toss', word: '깔끔',     count: 2800 },
    { appKey: 'toss', word: '자산관리', count: 2500 },
    { appKey: 'toss', word: '디자인',   count: 2200 },
    { appKey: 'toss', word: '편의',     count: 1900 },
    { appKey: 'toss', word: '고객센터', count: 1100 },
    { appKey: 'toss', word: '알림',     count: 890  },
    // 카카오
    { appKey: 'kakao', word: '편리',     count: 3200 },
    { appKey: 'kakao', word: '계좌개설', count: 2900 },
    { appKey: 'kakao', word: '이체',     count: 2600 },
    { appKey: 'kakao', word: '적금',     count: 2300 },
    { appKey: 'kakao', word: '간편',     count: 2100 },
    { appKey: 'kakao', word: '대출',     count: 1800 },
    { appKey: 'kakao', word: '고객센터', count: 1500 },
    { appKey: 'kakao', word: '빠름',     count: 1200 },
    { appKey: 'kakao', word: '연동',     count: 980  },
    { appKey: 'kakao', word: '오류',     count: 760  },
    // KB
    { appKey: 'kb', word: '복잡',   count: 2100 },
    { appKey: 'kb', word: '느림',   count: 1980 },
    { appKey: 'kb', word: 'UI',     count: 1760 },
    { appKey: 'kb', word: '오류',   count: 1540 },
    { appKey: 'kb', word: '로그인', count: 1320 },
    { appKey: 'kb', word: '주식',   count: 1100 },
    { appKey: 'kb', word: '증권',   count: 980  },
    { appKey: 'kb', word: '편의',   count: 870  },
    { appKey: 'kb', word: '불편',   count: 810  },
    { appKey: 'kb', word: '개선',   count: 720  },
    // 하나
    { appKey: 'hana', word: '복잡',   count: 1560 },
    { appKey: 'hana', word: '환전',   count: 1340 },
    { appKey: 'hana', word: '느림',   count: 1220 },
    { appKey: 'hana', word: '오류',   count: 1100 },
    { appKey: 'hana', word: '해외',   count: 980  },
    { appKey: 'hana', word: '불편',   count: 870  },
    { appKey: 'hana', word: '메뉴',   count: 760  },
    { appKey: 'hana', word: '이체',   count: 650  },
    { appKey: 'hana', word: '편의',   count: 540  },
    { appKey: 'hana', word: '개선',   count: 430  },
    // 우리
    { appKey: 'woori', word: '구식',   count: 1200 },
    { appKey: 'woori', word: 'UI',     count: 1100 },
    { appKey: 'woori', word: '포인트', count: 980  },
    { appKey: 'woori', word: '느림',   count: 870  },
    { appKey: 'woori', word: '이체',   count: 760  },
    { appKey: 'woori', word: '알림',   count: 650  },
    { appKey: 'woori', word: '이벤트', count: 580  },
    { appKey: 'woori', word: '오류',   count: 520  },
    { appKey: 'woori', word: '편리',   count: 460  },
    { appKey: 'woori', word: '개선',   count: 400  },
  ],
};
